export const videos = [
  {
    id: 1,
    title: "Deram vinagre",
    date: "13 de Outubro, 2025",
    text: "Saiba mais sobre a água da vida que e Jesus e o poder do Espirito Santo em sua vida.",
    videoUrl: "https://www.youtube.com/embed/48WyaGGwR_8",
    duration: 4.53,
  },

  {
    id: 2,
    title: "Esta vivo",
    date: "12 de Outtubro, 2025",
    text: "Ele ressucitou no terceiro dia e vive. Jesus morreu e sofreu por nós para que tenhamos vida e vida em abundancia.",
    videoUrl: "https://www.youtube.com/embed/EyF7PPSM3N4",
    duration: 3.19,
  },
  {
    id: 3,
    title: "Libertará",
    date: "12 de Outubro, 2025",
    text: "Conheça a Verdade e a Verdade os libertará, se o Filho os liberta, definitivamente estareis salvo.",
    videoUrl: "https://www.youtube.com/embed/XH_jYFJ1lJQ",
    duration: 3.22,
  },
  {
    id: 4,
    title: "Não brinca com Deus",
    date: "18 de Outubro, 2025",
    text: "As palavras tem poder, uma reflexão sobre observarmos as palavras que saem de nossa boca.",
    videoUrl: "https://www.youtube.com/embed/zPbUSTiyL0Y",
    duration: 2.48,
  },
  {
    id: 5,
    title: "O Leão",
    date: "17 de Setembro, 2025",
    text: "Jesus e o Leão da tribo de Judá",
    videoUrl: "https://www.youtube.com/embed/JTmeyIoKgMo",
    duration: 3.37,
  },
  {
    id: 6,
    title: "O muro caiu",
    date: "27 de Setembro, 2025",
    text: "O muro parecia uma tarefa impossível, mas o poder da fé derrubaram as muralhas.",
    videoUrl: "https://www.youtube.com/embed/7pv-q8yGk5s",
    duration: 4.05,
  },
  {
    id: 7,
    title: "O azeite",
    date: "12 de Setembro, 2025",
    text: "O poder da fé na vida de uma mulher",
    videoUrl: "https://www.youtube.com/embed/Ig_opomw6L4",
    duration: 4.37,
  },
];